// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace relay {
namespace api {

// service definition.
class StreamInvokeService final {
 public:
  static constexpr char const* service_full_name() {
    return "relay.api.StreamInvokeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::relay::api::HitWordResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>> AsynchitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>>(AsynchitWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>> PrepareAsynchitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>>(PrepareAsynchitWordsRaw(context, request, cq));
    }
    virtual ::grpc::Status sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::relay::api::SentenceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>> Asyncsentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>>(AsyncsentenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>> PrepareAsyncsentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>>(PrepareAsyncsentenceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>* AsynchitWordsRaw(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::HitWordResponse>* PrepareAsynchitWordsRaw(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>* AsyncsentenceRaw(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::relay::api::SentenceResponse>* PrepareAsyncsentenceRaw(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::relay::api::HitWordResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>> AsynchitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>>(AsynchitWordsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>> PrepareAsynchitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>>(PrepareAsynchitWordsRaw(context, request, cq));
    }
    ::grpc::Status sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::relay::api::SentenceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>> Asyncsentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>>(AsyncsentenceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>> PrepareAsyncsentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>>(PrepareAsyncsentenceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response, std::function<void(::grpc::Status)>) override;
      void hitWords(::grpc::ClientContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response, std::function<void(::grpc::Status)>) override;
      void sentence(::grpc::ClientContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>* AsynchitWordsRaw(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::relay::api::HitWordResponse>* PrepareAsynchitWordsRaw(::grpc::ClientContext* context, const ::relay::api::HitWordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>* AsyncsentenceRaw(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::relay::api::SentenceResponse>* PrepareAsyncsentenceRaw(::grpc::ClientContext* context, const ::relay::api::SentenceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_hitWords_;
    const ::grpc::internal::RpcMethod rpcmethod_sentence_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status hitWords(::grpc::ServerContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response);
    virtual ::grpc::Status sentence(::grpc::ServerContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_hitWords() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesthitWords(::grpc::ServerContext* context, ::relay::api::HitWordRequest* request, ::grpc::ServerAsyncResponseWriter< ::relay::api::HitWordResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_sentence() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsentence(::grpc::ServerContext* context, ::relay::api::SentenceRequest* request, ::grpc::ServerAsyncResponseWriter< ::relay::api::SentenceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_hitWords<WithAsyncMethod_sentence<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_hitWords() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::relay::api::HitWordRequest, ::relay::api::HitWordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::relay::api::HitWordRequest* request, ::relay::api::HitWordResponse* response) { return this->hitWords(context, request, response); }));}
    void SetMessageAllocatorFor_hitWords(
        ::grpc::MessageAllocator< ::relay::api::HitWordRequest, ::relay::api::HitWordResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::relay::api::HitWordRequest, ::relay::api::HitWordResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* hitWords(
      ::grpc::CallbackServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_sentence() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::relay::api::SentenceRequest, ::relay::api::SentenceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::relay::api::SentenceRequest* request, ::relay::api::SentenceResponse* response) { return this->sentence(context, request, response); }));}
    void SetMessageAllocatorFor_sentence(
        ::grpc::MessageAllocator< ::relay::api::SentenceRequest, ::relay::api::SentenceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::relay::api::SentenceRequest, ::relay::api::SentenceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sentence(
      ::grpc::CallbackServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_hitWords<WithCallbackMethod_sentence<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_hitWords() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_sentence() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_hitWords() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesthitWords(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_sentence() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestsentence(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_hitWords() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->hitWords(context, request, response); }));
    }
    ~WithRawCallbackMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* hitWords(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_sentence() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->sentence(context, request, response); }));
    }
    ~WithRawCallbackMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sentence(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_hitWords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_hitWords() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::relay::api::HitWordRequest, ::relay::api::HitWordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::relay::api::HitWordRequest, ::relay::api::HitWordResponse>* streamer) {
                       return this->StreamedhitWords(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_hitWords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status hitWords(::grpc::ServerContext* /*context*/, const ::relay::api::HitWordRequest* /*request*/, ::relay::api::HitWordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedhitWords(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::relay::api::HitWordRequest,::relay::api::HitWordResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sentence : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_sentence() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::relay::api::SentenceRequest, ::relay::api::SentenceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::relay::api::SentenceRequest, ::relay::api::SentenceResponse>* streamer) {
                       return this->Streamedsentence(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_sentence() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sentence(::grpc::ServerContext* /*context*/, const ::relay::api::SentenceRequest* /*request*/, ::relay::api::SentenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedsentence(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::relay::api::SentenceRequest,::relay::api::SentenceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_hitWords<WithStreamedUnaryMethod_sentence<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_hitWords<WithStreamedUnaryMethod_sentence<Service > > StreamedService;
};

}  // namespace api
}  // namespace relay


#endif  // GRPC_service_2eproto__INCLUDED
